"""add financials table

Revision ID: 5f7fd30113b1
Revises: 8bf8964e941a
Create Date: 2026-08-18 21:58:24.862622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7fd30113b1'
down_revision: Union[str, Sequence[str], None] = '8bf8964e941a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('trailing_pe', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('price_to_book', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_to_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('return_on_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('return_on_assets', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', name='uq_financials_stock_id')
    )
    op.create_index(op.f('ix_financials_stock_id'), 'financials', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financials_stock_id'), table_name='financials')
    op.drop_table('financials')
    # ### end Alembic commands ###
