"""add company_profiles

Revision ID: 74b2071c0d29
Revises: a844177fa25e
Create Date: 2026-09-06 20:01:18.460302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b2071c0d29'
down_revision: Union[str, Sequence[str], None] = 'a844177fa25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('ceo', sa.String(length=200), nullable=True),
    sa.Column('employees', sa.BigInteger(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', name='uq_company_profiles_stock_id')
    )
    op.create_index(op.f('ix_company_profiles_stock_id'), 'company_profiles', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_profiles_stock_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
