"""add financial_periods table

Revision ID: a844177fa25e
Revises: b0f48fb7c939
Create Date: 2026-09-05 18:38:01.025666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a844177fa25e'
down_revision: Union[str, Sequence[str], None] = 'b0f48fb7c939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'period_end', 'period_type', name='uq_financial_periods_stock_period')
    )
    op.create_index(op.f('ix_financial_periods_stock_id'), 'financial_periods', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_periods_stock_id'), table_name='financial_periods')
    op.drop_table('financial_periods')
    # ### end Alembic commands ###
