"""add alpha_scores table

Revision ID: b0f48fb7c939
Revises: ed7bb907ca7c
Create Date: 2026-08-19 12:34:54.096787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0f48fb7c939'
down_revision: Union[str, Sequence[str], None] = 'ed7bb907ca7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fundamental', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('technical', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('composite', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_alpha_scores_symbol_date')
    )
    op.create_index(op.f('ix_alpha_scores_symbol'), 'alpha_scores', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alpha_scores_symbol'), table_name='alpha_scores')
    op.drop_table('alpha_scores')
    # ### end Alembic commands ###
